# Prometheus configuration for Trading System monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trading-system'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "trading_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Trading System Application
  - job_name: 'trading-system'
    static_configs:
      - targets: ['trading-system:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node metrics for system monitoring
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Kafka Connect metrics
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083']
    scrape_interval: 30s
    metrics_path: /metrics

# Remote write configuration (for long-term storage if needed)
# remote_write:
#   - url: "http://timescaledb-prometheus-adapter:9201/write"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'trading_.*'
#         action: keep
